site_name: Dokumentacja projektu AI DNA Assembler
use_directory_urls: false

theme:
  name: material

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            heading_level: 2

nav:
  - Strona Główna: index.md
  - Assembler w Python: dna_asm_python.md
  - Generator losowego genomu: random_generator_and_sequencer.md
  - Moduły Rust: rust.md